### ISSUE TITLE
Time Flys isnt a correct word, it should be Time Flies 

### ISSUE THREAD

**Issue by Osama-qa** [lntechadmin/ShowOrGhost-Latest#297]
![Time Flies.png](https://images.zenhubusercontent.com/62b95e0c497fa5496754651f/e56c12cc-55c1-437c-9d36-fbc642c9b09e)

**Comment by Talhabai** [comment]
@Osama-qa please provide image.

**Comment by ArslanBaig1** [comment]
![image.png](https://images.zenhubusercontent.com/60509117cde27733acd0cf68/c4a2ddee-cb69-4a1a-84cf-4ae94972b7ea)
